### ISSUE TITLE
yaml scanner error

### ISSUE THREAD

**Issue by fy-kenny** [yaml/yaml#51]
```console
10:45:17.728 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from location 'classpath:/application-local.yml'
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:554)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadForFileExtension(ConfigFileApplicationListener.java:488)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:467)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$6(ConfigFileApplicationListener.java:448)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$7(ConfigFileApplicationListener.java:447)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:444)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:332)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:207)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:190)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.seventh.hospital.app.Application.main(Application.java:25)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 3, column 11:
        name: @project.artifactId@
              ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:419)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:161)
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:134)
	at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:75)
	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadDocuments(ConfigFileApplicationListener.java:572)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:526)
	... 23 common frames omitted
```

backgroup: 
file application.yml
```yaml
spring:
  application:
    name: @project.artifactId@
```
added:  tags in maven pom.xml
```xml
<resources>
            <resource>

            </resource>
</resources>
```

It will work well when I remove this tags.
so is it a compatible bug between yaml and maven or maven plugin

Please give me a hand , THX:D

**Comment by fy-kenny** [comment]
# I have found the root cause.

* We should override the `resources` block totally  when we do customization
```xml
<resources />
``` 
* because it can not be extended other resources features from the parent project
like
```java
// call parent
super.resources();
// customzie self
this.resource();
```
* So, we should add `resource` like this, or copy `resource` block from `spring-boot-starter-parent-*.pom`.
```xml
<resources>
    <resource>
         <filtering>true</filtering><!-- **This line is important**, it will replace maven property placeholders in yaml files using actual value of maven property in file pom.xml -->
         <directory>${basedir}/src/main/resources</directory>
          <!-- ... for details, please link to spring-boot-starter-parent-*.pom -->
    </resource>
</resources>
```

## **PAY ATTENTION PLEASE!!! 
---
This line is very important , it will replace maven property placeholders in yaml files using actual value of maven properties in file pom.xml
---
`<filtering>true</filtering>`

Please comment feel free if you have any other information.
---
BTW, it a lot reply or answer from internet 
1. quotes @@ with ' or ",
2. donot use symbol @ 
3. customize `resource.delimiter`
4. problem of you build
actually it help me found the cause, but can not resolve my trouble, not suitable for my situation.
It will place the maven properties placeholder with the literal string @project.artifactId@, and 
my application name is @project.artifactId@. it's very strange,  and you?

EVEN, Something ridiculous happened,
I met Selckin in #maven grou on irc.freenode.net, He command me closed issue
and blame me sent the same issue to other groups like #java-talk 
bellow is original message:
```
<fy_kenny> https://github.com/yaml/yaml/issues/51
<selckin> please close that issue nothing to do with yaml project
<selckin> and stop spamming that link in every irc channel like the entireled spammer you are
* px3 (~Adium@p57969BFD.dip0.t-ipconnect.de) Quit (Ping timeout: 258 seconds)
<fy_kenny> whats your means
<fy_kenny> it's maven issue? 
* Looking up selckin user info...
<fy_kenny> why you command me to close the issue? Do you already have a solution?
-
selckin is ~selckin@unaffiliated/selckin * selckin
selckin on #java-talk #maven 
selckin using barjavel.freenode.net Paris, FR, EU
selckin is using a secure connection
selckin has been idle 6mins 53secs, signed on Mon Mar 23 21:06:30 2020
selckin is logged in as selckin
selckin End of /WHOIS list.
-
<fy_kenny> please allow anyone to ask question if you have not right solution or recommendation. even you can not figure out any helpful information @selckin
<selckin> fy_kenny: go away and never contact an open source project again
<fy_kenny> ？
<fy_kenny> this time is my first time
<selckin> well you are the kind of person that makes maintainers not want to provide help
* px3 (~Adium@p57969BFD.dip0.t-ipconnect.de) has joined #maven
<fy_kenny> is open source project belong to you only
<fy_kenny> I donot need so much help from you 
<selckin> now you're gonna play victum to pretend you don't know what you're doing to get help anyway
<fy_kenny> Please close you mouth to pollute open source social 
<fy_kenny> Narrow-minded you shold leave away
* Retrieving #maven modes...
<fy_kenny> I don't want to read any message from you
```
but a lot of spam message from him, This is a ridiculous thing! I have reason to think that
he have sent a lot of spam message everyday.
```
#java-talk
<javabot> fy_kenny's title: "yaml scanner error · Issue #51 · yaml/yaml · GitHub"
<selckin> but the expensive mouses should still do quite good on those survices
<selckin> but the mouse pad just solves it too
<selckin> and the cloth ones also don't feel cold on your arm
<db> yeah maybe.
<selckin> https://gfycat.com/scrawnyvagueguanaco
<javabot> selckin's title: "She Has A Fucking Thermometer In Her Hand! GIF by MyNameGifOreilly | Gfycat"
<selckin> flawless
<selckin> spreading the virus till you have no more students!
<selckin> vaaacation
<db> lol
<db> that looks like Thailand.
<db> and I think it's a joke.
<selckin> red shirt guy is a good actor then
<selckin> i think the thermometer is too slow, no patience
<selckin> and still need to be able to say you took the temperature to bypass bureaucracy
```
I hope peace and the same to you 🤝
